version: 2
jobs:
  build:
    docker:
      - image: ana12334/dockerimage:aman
         auth
           username: ana12334
           password: ana@12345

    steps:
      - checkout
      - run: sudo docker run -d -p 80:80 ana12334/dockerimage:aman --name aman
