version: 2.1
jobs:
  build:
    machine: true
    docker:
      - image: ana12334/dockerimage:aman
        auth:
          username: ana12334
          password: ana@12345

    steps:
      - checkout
      - run: docker build -t ana12334/dockerimage:aman .
      - run: sudo docker tag ana12334/dockerimage:aman:latest aman:v6
      - run: sudo docker push ana12334/dockerimage:aman:v6
workflows:
  build:
    jobs:
      - build  
